export const ESCROW_UI = {
  badge: "Պաշտպանված գործարք",
  amountLine: (contract: string, receives: string, pct: number, fee: string) =>
    `Գումար՝ ${contract} · կատարողը կստանա ${receives} (միջնորդավճար ${pct}% = ${fee})`,
  bankTitle: "Բանկային փոխանցում",
  receiver: "Ստացող",
  bank: "Բանկ",
  account: "Հաշիվ",
  amount: "Գումար",
  paymentCode: "Պարտադիր նշում",
  noteOptional: "Նշում (ոչ պարտադիր)",
  notePlaceholder: "Օր. փոխանցման ամսաթիվ",
  submitPayment: "Փոխանցել եմ · ուղարկել ստուգման",
  paymentReview: "Ստուգում ենք մուտքը։ Կատարողը կսկսի աշխատանքը հաստատումից հետո։",
  waitTransfer: "Սպասում ենք պատվիրատուի փոխանցմանը։ Մինչև հաստատումը աշխատանքը մի սկսեք։",
  funded:
    "Փոխանցումը հաստատված է ադմինի կողմից։ Այժմ կողմերը կարող եք սկսել համագործակցությունը։",
  releaseCta: "Աշխատանքն ավարտված է · ազատել գումարը",
  releasePending: "Հաստատված է · սպասում ենք ադմինի փոխանցմանը կատարողին։",
  disputed: "Վեճի ընթացքում է։",
  openDispute: "Բացել վեճ",
  disputePlaceholder: "Նկարագրեք խնդիրը (առնվազն 10 նիշ)",
  submit: "Ուղարկել",
  cancel: "Չեղարկել",
  awaitingContract: "Պաշտպանված գործարքը կակտիվանա պայմանագրի երկկողմանի հաստատումից հետո։",
  toastFail: "Չհաջողվեց",
  toastRetry: "Փորձեք նորից։",
  toastNetwork: "Ցանցի խնդիր",
  toastPaymentOk: "Ուղարկված է",
  toastPaymentOkBody: "Ադմինը կստուգի մուտքը։",
  toastReleaseOk: "Հաստատված է",
  toastReleaseOkBody: "Ադմինը կփոխանցի գումարը կատարողին։",
  toastDisputeShort: "Պատճառ",
  toastDisputeShortBody: "Գրեք առնվազն 10 նիշ։",
  toastDisputeOk: "Վեճը բացված է",
  toastDisputeOkBody: "Ադմինը կուսումնասիրի։",
} as const;
