export const ROUTES = {
  home: "/",
  howItWorks: "/how-it-works",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  categories: "/categories",
  categoryDetail: (id: string) => `/categories/${id}`,
  terms: "/terms",
  privacy: "/privacy",
  account: "/account",
  accountSettings: "/account/settings",
  accountVerification: "/account/verification",
  accountVerifyTelegram: "/account/verify-telegram",
  accountVerify: "/account/verify",
  verifyEmail: "/verify-email",
  myTenders: "/tenders?scope=my",
  bidHistory: "/tenders?scope=bids",
  likedTenders: "/tenders?scope=liked",
  tenders: "/tenders",
  tenderDetail: (id: string) => `/tenders/${id}`,
  editTender: (id: string) => `/tenders/${id}/edit`,
  /** Միայն COMPLETED AWARDED զույգ՝ փոխադարձ գնահատական։ */
  tenderReview: (id: string) => `/tenders/${id}/review`,
  createTender: "/tenders/new",
  userProfile: (id: string) => `/users/${id}`,
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    tenders: "/admin/tenders",
    bids: "/admin/bids",
    verifications: "/admin/verifications",
    transactions: "/admin/transactions",
    subscriptions: "/admin/subscriptions",
    reviews: "/admin/reviews",
    tenderComplaints: "/admin/tender-complaints",
    services: "/admin/services",
  },
  sections: {
    howItWorks: "/how-it-works",
    features: "/#features",
    providers: "/providers",
  },
};
