export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  categories: "/categories",
  terms: "/terms",
  privacy: "/privacy",
  account: "/account",
  accountSettings: "/account/settings",
  accountVerification: "/account/verification",
  myTenders: "/tenders?scope=my",
  bidHistory: "/tenders?scope=bids",
  tenders: "/tenders",
  tenderDetail: (id: string) => `/tenders/${id}`,
  /** Միայն COMPLETED AWARDED զույգ՝ փոխադարձ գնահատական։ */
  tenderReview: (id: string) => `/tenders/${id}/review`,
  createTender: "/tenders/new",
  admin: {
    dashboard: "/admin",
    users: "/admin/users",
    tenders: "/admin/tenders",
    bids: "/admin/bids",
    verifications: "/admin/verifications",
    transactions: "/admin/transactions",
    subscriptions: "/admin/subscriptions",
    reviews: "/admin/reviews",
    tenderComplaints: "/admin/tender-complaints",
    services: "/admin/services",
  },
  sections: {
    howItWorks: "/#how-it-works",
    features: "/#features",
    providers: "/#providers",
  },
};
